package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Eshan276/signoz_hackathon/internal/detect"
)

// Config controls how the override file is rendered.
type Config struct {
	// Endpoint is the OTLP HTTP endpoint services export to.
	Endpoint string
	// UseHostGateway adds extra_hosts mapping host.docker.internal. Required on
	// Linux Docker Engine, where that name does not resolve by default; harmless
	// on Docker Desktop.
	UseHostGateway bool
}

// DefaultConfig targets a SigNoz stack running on the same host.
func DefaultConfig() Config {
	return Config{
		Endpoint:       "http://host.docker.internal:4318",
		UseHostGateway: true,
	}
}

// OverrideFilename is what we generate. Compose merges it automatically, so the
// user's own file stays untouched and `rm` is a complete uninstall.
const OverrideFilename = "docker-compose.override.yml"

// Override renders docker-compose.override.yml for the instrumented services.
//
// Written by hand rather than marshalled from a struct so the output keeps its
// comments and ordering. Users read this file — it is part of the UX, not a
// build artifact.
func Override(services []detect.Service, cfg Config) string {
	var b strings.Builder

	b.WriteString("# Generated by `signoz init`.\n")
	b.WriteString("#\n")
	b.WriteString("# Docker Compose merges this with your docker-compose.yml automatically,\n")
	b.WriteString("# which is why your own compose file was not modified.\n")
	b.WriteString("#\n")
	b.WriteString("# To remove all instrumentation:  rm " + OverrideFilename + "\n")
	b.WriteString("# To disable it temporarily:      set SIGNOZ_INIT_DISABLE=1 on a service\n")
	b.WriteString("\nservices:\n")

	instrumented := 0
	for _, s := range services {
		if !s.Instrument {
			continue
		}
		switch s.Runtime {
		case detect.RuntimePython:
			b.WriteString(pythonService(s, cfg))
			instrumented++
		case detect.RuntimeNode:
			b.WriteString(nodeService(s, cfg))
			instrumented++
		}
	}

	if instrumented == 0 {
		b.WriteString("  # No instrumentable services were selected.\n")
	}
	return b.String()
}

func pythonService(s detect.Service, cfg Config) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\n  %s:\n", s.Name)
	if s.Framework != "" {
		fmt.Fprintf(&b, "    # detected: Python / %s\n", s.Framework)
	} else {
		b.WriteString("    # detected: Python\n")
	}

	b.WriteString("    environment:\n")
	// sitecustomize is imported automatically by the interpreter at startup, which
	// is what makes this zero-touch: no app code and no Dockerfile CMD change.
	b.WriteString("      PYTHONPATH: /otel\n")
	fmt.Fprintf(&b, "      OTEL_SERVICE_NAME: %s\n", s.Name)
	fmt.Fprintf(&b, "      OTEL_EXPORTER_OTLP_ENDPOINT: %s\n", cfg.Endpoint)
	b.WriteString("      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf\n")
	// Traceloop reads its target from this var; the api_endpoint argument alone
	// silently exports nowhere.
	fmt.Fprintf(&b, "      TRACELOOP_BASE_URL: %s\n", cfg.Endpoint)
	b.WriteString("      TRACELOOP_TELEMETRY: \"false\"\n")
	b.WriteString("      OTEL_SEMCONV_STABILITY_OPT_IN: gen_ai_latest_experimental\n")

	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - ./%s/python:/otel:ro\n", AssetDir)
	b.WriteString(hostGateway(cfg))
	return b.String()
}

func nodeService(s detect.Service, cfg Config) string {
	var b strings.Builder
	fmt.Fprintf(&b, "\n  %s:\n", s.Name)
	if s.Framework != "" {
		fmt.Fprintf(&b, "    # detected: Node.js / %s\n", s.Framework)
	} else {
		b.WriteString("    # detected: Node.js\n")
	}

	b.WriteString("    environment:\n")
	b.WriteString("      NODE_OPTIONS: --require /otel/otel-bootstrap.js\n")
	fmt.Fprintf(&b, "      OTEL_SERVICE_NAME: %s\n", s.Name)
	fmt.Fprintf(&b, "      OTEL_EXPORTER_OTLP_ENDPOINT: %s\n", cfg.Endpoint)
	b.WriteString("      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf\n")

	b.WriteString("    volumes:\n")
	fmt.Fprintf(&b, "      - ./%s/node:/otel:ro\n", AssetDir)
	b.WriteString(hostGateway(cfg))
	return b.String()
}

func hostGateway(cfg Config) string {
	if !cfg.UseHostGateway {
		return ""
	}
	return "    # Linux Docker Engine does not resolve host.docker.internal by default.\n" +
		"    extra_hosts:\n" +
		"      - \"host.docker.internal:host-gateway\"\n"
}

// AssetsFor returns the assets that must exist on disk for these services.
func AssetsFor(services []detect.Service) []Asset {
	var needPython, needNode bool
	for _, s := range services {
		if !s.Instrument {
			continue
		}
		switch s.Runtime {
		case detect.RuntimePython:
			needPython = true
		case detect.RuntimeNode:
			needNode = true
		}
	}

	var out []Asset
	if needPython {
		out = append(out, PythonAssets...)
	}
	if needNode {
		out = append(out, NodeAssets...)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Target < out[j].Target })
	return out
}
